spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: [ classpath:/config ]
  profiles:
    active: native
#  security:
#    user:
#      name: mcs
#      password: iammicroservice

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://admin:admin@${EUREKA_HOST:localhost}:8761/eureka/

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"